app = "hello-sample-api"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[env]
  RAILS_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[deploy]
  release_command = "bin/rails fly:release"
