name: Run vitest,cypress,eslint

on:
  push:
    branches:
      - main
jobs:
  build:
    name: verify
    runs-on: ubuntu-latest
    container:
      image: node:18.16.0
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: npm install
        run: |
          cd front
          npm install

        - name: verify
        run: |
          cd front
          npm run lint
          npm run test:unit
          npm run test:e2e

