name: Run vitest,cypress,eslint

on:
  push:
    branches:
      - main
jobs:
  build:
    name: verify
    runs-on: ubuntu-latest
    container:
      image: node:18.16.0

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: verify
        run: |
          cd front
          npm run lint
          npm run test:unit

      - name: checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run start

